name: E2E

on: 
  push:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v1
      - run: npm install
      - run: npx run cypress
      - run: ls-la
          
      - name: Upload cypress video
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-results
          path: cypress
          retention-days: 1
