name: E2E

on: 
  push:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: cypress-io/github-action@v5
      - run: npm install
      - run: npm run cypress:chrome
      - run: ls-la
          
      - name: Upload cypress video
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-results
          path: cypress
          retention-days: 1
