name: E2E

on: 
  push:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npx happo-e2e --allow-failures -- npx cypress run
        env:
          HAPPO_API_KEY: 5661ccef59
          HAPPO_API_SECRET: 20b0bfa2a307e18629ae22008
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          
      - name: Upload cypress video
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-results
          path: cypress
          retention-days: 1
